PCMS interpolation functionality
SCOREC/pcms pull request #148
Opened 2024-12-18 08:38 UTC by jacobmerson

This pull request brings in @abhiyan123 initial changes for dealing with RBF field interpolations. I have gotten this into a state where it can be merged with develop and tests/compilation passes.

However, I have not done a formal review of this code and there are a some issues that need to be addressed before merging with develop.

@Fuad-HH I have requested you as a reviewer. Please take a look and see if you have any input, questions, etc.

@cwsmith relevant code for our discussion on surface fitting is here. Unfortunately, getting everything merged took some time and I have not had time to do the proper review I wanted before our meeting. Let me know if you prefer to push back that discussion until Thursday/Friday.

2024-12-18 14:40 UTC, cwsmith commented
@jacobmerson Thanks for the heads up.  Thursday or Friday works for me.

2024-12-18 16:26 UTC, Fuad-HH commented on src/pcms/interpolator/MLSInterpolation.hpp
> +
I noticed some style issues like this previously. I am talking about the blank lines between each line of code.

2024-12-18 16:26 UTC, Fuad-HH commented on src/pcms/interpolator/queue_visited.hpp
> +class queue
The class name could be `Queue` (PascalCase) to follow the PCMS style.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +KOKKOS_INLINE_FUNCTION
This comment should be expanded to explain the algorithm. Also, need to explain why this is a kokkos inline function that takes a host array. It's not clear to me that this can be called on the device.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +int basisSize(const Kokkos::View<int**, Kokkos::HostSpace>& array)
Why is this kokkos inline function? Can it be called from device?

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void basisSliceLengths(Kokkos::View<int**, Kokkos::HostSpace>& array)
Since this is not templated definition should be in cpp file.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +{
Move definition to cpp file.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +               Coord& p)
Naming is not consistent.
Take views by const ref.
Since not templated. Definition in cpp file.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void CreateVandermondeMatrix(ScratchMatView vandermonde_matrix,
Naming not consistent.
Take vies by const ref.
Definition in cpp file (since this is kokkos stuff we may want it in template definition file) we can discuss.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +KOKKOS_INLINE_FUNCTION void PhiVector(ScratchVecView Phi,
Naming
Views by const ref

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void ScaleColumnTransMatrix(ScratchMatView result_matrix,
Naming
Views by const ref

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +// KOKKOS_INLINE_FUNCTION
All commented out code needs to be removed before merge.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void dot_product(member_type team, const ScratchVecView& result_sub,
Why are we using this instead of kokkos kernels version? If there is a need it needs to have a comment explaining it.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +// matrix matrix multiplication
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +struct ResultConvertNormal
Please add comments explaining what each of these members will hold.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +ResultConvertNormal ConvertNormalEq(const ScratchMatView matrix,
Update naming and views by reference

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +//// moment matrix
Remove commented code

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void SolveMatrix(const ScratchMatView square_matrix, const ScratchVecView rhs,
Naming, pass by reference.

Please add comment explaining what this function is doing, inputs/ outputs.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +void SolveMatrix(const ScratchMatView square_matrix, const ScratchVecView rhs,
Ok. I see the comment now...please use doxygen comment style. No spacing between comment and function.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +  //    KokkosBlas::Experimental::TeamGemv<member_type,
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +#define MLS_COEFFICIENTS_HPP
PCMS_INTERPOLATOR_MLS_COEFFICIENTS_HPP

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +  double ds_sq = dx * dx + dy * dy;
Is this assuming 2D?

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSCoefficients.hpp
> +  team.team_barrier();
Let's double check if this barrier is needed.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +Write<Real> mls_interpolation(const Reals source_values,
Needs doxygen comment

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +Write<Real> mls_interpolation(const Reals source_values,
Why do we return a write? We are using kokkos arrays most other places. It might make sense but we need to document.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +  // nvertices_target);
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +  assert(scratch_size > shared_size &&
Should use the PCMs assert/logging function. Pretty much always want this assert to be active.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +{
Should have PCMS_FUNCTION_TIMER so we can see this in our profiles.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +  Kokkos::parallel_reduce(
Use kokkos max element. Clearer intent: https://kokkos.org/kokkos-core-wiki/API/algorithms/std-algorithms/all/StdMaxElement.html

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +  Kokkos::parallel_for(
Needs comment explaining functionality of this loop. Likely should be factored into separate function.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +      // stores P^T Q
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +      //	Kokkos::deep_copy(lower, 0.0);
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +      Kokkos::parallel_for(Kokkos::TeamThreadRange(team, basis_size),
Could this be done with kokkos kernels fill instead? Intent would be more clear.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLSInterpolation.hpp
> +      //      // sum phi
Remove commented code.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLS_rbf_options.cpp
> +// TODO add PCMS namespace to all interpolation code
This should be done before merge.

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/MLS_rbf_options.hpp
> +#define MLS_RBF_OPTIONS_HPP
Prefix with PCMS_INTERPOLATOR

2024-12-23 03:44 UTC, jacobmerson commented on src/pcms/interpolator/multidimarray.hpp
> +int calculateIndex(const IntVecView& dimensions, const int* indices)
Why do we have these. Kokkos views should handle indexing for us.

2025-01-14 19:26 UTC, Fuad-HH commented on src/pcms/interpolator/CMakeLists.txt
> +find_package(KokkosKernels REQUIRED)
For me, it worked with `4.1.00` for both `kokkos` and `kokkos-kernels` on SCOREC rhel9 OpenMP Serial configuration. I also tried the `develop` branch but it failed for `mdspan`.

2025-01-17 18:36 UTC, jacobmerson commented on src/pcms/interpolator/CMakeLists.txt
> +    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
just the `target_include_directories` not `target_link_libraries`

2025-01-23 00:51 UTC, Fuad-HH requested changes

2025-01-23 00:51 UTC, Fuad-HH commented on test/test_rbf_interp.cpp
A test for one mesh vertex to another mesh vertex is also needed.

2025-01-23 00:51 UTC, Fuad-HH commented on src/pcms/interpolator/MLS_rbf_options.cpp
> +    OMEGA_H_CHECK_PRINTF(r_sq > 0,
Why is it not allowed for `r_sq` to be 0? I think, it will occur when it has a support location concurrent to a target which has a very high chance of occurrence in regular meshes.

2025-01-23 02:25 UTC, Fuad-HH commented on src/pcms/interpolator/MLS_rbf_options.cpp
> +    OMEGA_H_CHECK_PRINTF(r_sq > 0,
I have checked ([see here](https://github.com/Fuad-HH/pcms/blob/c8a268e1f35023113a63c87240f2720570586b78/test/test_interpolation_class.cpp#L142)), and it works when there is no coincident source and target. Although the Phi may go to infinity for r_sq = 0, there needs to be a solution for practicality.

2025-01-24 16:37 UTC, jacobmerson reviewed
I didn't get all the way through this, but there are a lot of changes that look like they are just modifications to the whitespace. We need to remove these whitespace changes from the current pull request. I'm looking into a strategy to have `clang-format` in CI/CD to make this easier to handle in the future.

2025-01-24 16:37 UTC, jacobmerson commented on ]
This file looks like you may have accidentally saved the commit message. Please remove it.

2025-03-17 04:51 UTC, merged